version: "3"
services:
  compra_cafe_db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: cafe
      POSTGRES_USER: cafe
      POSTGRES_DB: compra_cafe
    ports:
      - "5433:5432"

volumes:
  db-data:
    driver: local